# -*- coding: utf-8 -*-
"""wordcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlee9XhaCcr70fOMQOyUadxJXELh8Vhg
"""

# ecercice 1
# author : Beyrouthi
# state : ongoing

# ecercice 2
# author : Beyrouthi
# state : ongoing

# ecercice 3
# author : Beyrouthi
# state : ongoing

# ecercice 4
# author : Beyrouthi
# state : ongoing

# ecercice 5
# author : Beyrouthi
# state : ongoing

# ecercice 6
# author : Beyrouthi
# state : ongoing